/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author VIKASH
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        br = new javax.swing.JLabel();
        CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(190, 190));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 40));

        CB.setBackground(new java.awt.Color(153, 153, 153));
        CB.setForeground(new java.awt.Color(255, 255, 255));
        CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    *", "   **", "  ***", " ****", "*****" }));
        CB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S U B M I T ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, 30));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, 30));

        jScrollPane1.setEnabled(false);

        tt.setEditable(false);
        tt.setBackground(new java.awt.Color(204, 0, 204));
        tt.setColumns(20);
        tt.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        tt.setForeground(new java.awt.Color(255, 255, 255));
        tt.setRows(5);
        tt.setText("THIS PROJECT HAS BEEN CREATED BY \nMOHIT(ROLL NO. 26) AND MUKUL(ROLL NO. 27)\nOF CLASS XII-A (12th A) OF S.V.M. PUBLIC \nSCHOOL.\nTHIS PROJECT WAS COMPLETED BY BOTH MOHIT \nAND MUKUL WITH THEIR OWN CREATIVITY AND\nSKILLS.\nTHIS APPLICATION HELPS YOU TO MANAGE YOUR \nBAKERY AND CAFE SHOP \n\n              R A T E  U S\n\n      NAME :  ");
        tt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttMouseClicked(evt);
            }
        });
        tt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ttKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);

        // TODO add your handling code here:
    }//GEN-LAST:event_brMouseDragged

    private void ttKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttKeyPressed

    private void ttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttMouseClicked
new home().setVisible(true);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_ttMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        String A =(String)CB.getSelectedItem();
        String b= t1.getText();
        
           try{
            Class.forName("java.sql.Driver");
            Connection co = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= co.createStatement();
        
                
   
               
            String q = "insert into rate values('"+A+"','"+b+"');";
            s.executeUpdate(q);
               JOptionPane.showMessageDialog(null,"THANKS FOR RATING US "+A+" STARS");
           }catch (Exception r){
               JOptionPane.showMessageDialog(null,""+r.getSuppressed());
           }
    
           
           
           
              


        

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB;
    private javax.swing.JLabel br;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea tt;
    // End of variables declaration//GEN-END:variables
}
