/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VIKASH
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        
        
        
          //time
         new Timer(1000, new ActionListener(){
         @Override
         
            public void actionPerformed(ActionEvent e) {
                LocalDateTime ldt =LocalDateTime.now();
                 try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= c.createStatement();
            String q = "select curtime(),curdate() ;";
            ResultSet rs=s.executeQuery(q);
            if(rs.next()){

                
                
                 String z=rs.getString("curtime()");
                 String y=rs.getString("curdate()");
                 
                      
                  tim.setText(z);
                  dat.setText(y);
               

            }

        }

        catch (Exception qe){
            JOptionPane.showMessageDialog(null,""+qe.getMessage());
        }
            

            }
        }).start();
        
         
    
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DATE = new javax.swing.JPanel();
        dat = new javax.swing.JLabel();
        TIME = new javax.swing.JPanel();
        tim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        br = new javax.swing.JLabel();
        J = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        SET = new javax.swing.JLabel();
        AU = new javax.swing.JLabel();
        hom = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        FOOD = new javax.swing.JLabel();
        SUP = new javax.swing.JLabel();
        WAGES = new javax.swing.JLabel();
        SALE = new javax.swing.JLabel();
        STOCK = new javax.swing.JLabel();
        EMP = new javax.swing.JLabel();
        bil = new javax.swing.JLabel();
        nc = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        nc8 = new javax.swing.JLabel();
        ADD = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(110, 110));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DATE.setBackground(new java.awt.Color(153, 0, 204));

        dat.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DATELayout = new javax.swing.GroupLayout(DATE);
        DATE.setLayout(DATELayout);
        DATELayout.setHorizontalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DATELayout.setVerticalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 40));

        TIME.setBackground(new java.awt.Color(153, 0, 204));

        tim.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        tim.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TIMELayout = new javax.swing.GroupLayout(TIME);
        TIME.setLayout(TIMELayout);
        TIMELayout.setHorizontalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TIMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        TIMELayout.setVerticalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.JPG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 40));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.JPG"))); // NOI18N
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        J.setBackground(new java.awt.Color(153, 0, 204));

        back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        SET.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SET.setForeground(new java.awt.Color(255, 255, 255));
        SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SETTINGS.png"))); // NOI18N
        SET.setText("S E T T I N G S ");
        SET.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETMouseExited(evt);
            }
        });

        AU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AU.setForeground(new java.awt.Color(255, 255, 255));
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png"))); // NOI18N
        AU.setText("A B O U T  U S ");
        AU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JLayout = new javax.swing.GroupLayout(J);
        J.setLayout(JLayout);
        JLayout.setHorizontalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLayout.createSequentialGroup()
                .addGap(0, 258, Short.MAX_VALUE)
                .addComponent(back))
            .addGroup(JLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JLayout.setVerticalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLayout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AU)
                .addGap(13, 13, 13))
        );

        jPanel1.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 560));

        hom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.JPG"))); // NOI18N
        hom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homMouseClicked(evt);
            }
        });
        jPanel1.add(hom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "F O O D A V A I L A B L E", "  P R I C E "
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        tb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tb);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, 170));

        jLabel2.setText("S H O W     A V A I L A B L E     P R O D U C T S ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        sp.setBackground(new java.awt.Color(255, 255, 255));
        sp.setBorder(null);
        sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sp.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        sp.setDoubleBuffered(true);
        sp.setFocusCycleRoot(true);
        sp.setInheritsPopupMenu(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FOOD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FOOD.setForeground(new java.awt.Color(255, 0, 204));
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients.png"))); // NOI18N
        FOOD.setText("I N G R E D I E N T S");
        FOOD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOODMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FOODMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FOODMouseExited(evt);
            }
        });
        jPanel2.add(FOOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 110));

        SUP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SUP.setForeground(new java.awt.Color(0, 102, 255));
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.png"))); // NOI18N
        SUP.setText("S U P P L I E R");
        SUP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUPMouseExited(evt);
            }
        });
        jPanel2.add(SUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 110));

        WAGES.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WAGES.setForeground(new java.awt.Color(255, 255, 0));
        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages.png"))); // NOI18N
        WAGES.setText("W A G E S");
        WAGES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WAGES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WAGESMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WAGESMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WAGESMouseExited(evt);
            }
        });
        jPanel2.add(WAGES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 110));

        SALE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SALE.setForeground(new java.awt.Color(102, 0, 255));
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png"))); // NOI18N
        SALE.setText("S A L E S");
        SALE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SALE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SALEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SALEMouseExited(evt);
            }
        });
        jPanel2.add(SALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 110));

        STOCK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        STOCK.setForeground(new java.awt.Color(255, 153, 51));
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks.png"))); // NOI18N
        STOCK.setText("S T O C K S");
        STOCK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STOCK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STOCKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STOCKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STOCKMouseExited(evt);
            }
        });
        jPanel2.add(STOCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 110));

        EMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EMP.setForeground(new java.awt.Color(51, 0, 255));
        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees.png"))); // NOI18N
        EMP.setText("E M P L O Y E E S");
        EMP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EMPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EMPMouseExited(evt);
            }
        });
        jPanel2.add(EMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 230, 110));

        bil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bil.setForeground(new java.awt.Color(153, 255, 0));
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png"))); // NOI18N
        bil.setText("B  I  L  L ");
        bil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilMouseExited(evt);
            }
        });
        jPanel2.add(bil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 110));

        nc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nc.setForeground(new java.awt.Color(102, 204, 255));
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer1.png"))); // NOI18N
        nc.setText("N E W  C U S T O M E R");
        nc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ncMouseExited(evt);
            }
        });
        jPanel2.add(nc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 260, 110));

        sp.setViewportView(jPanel2);

        jPanel1.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 40, -1, 540));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("    B   I   L   L ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("I N F I N I T E   B A K E R S  &  C A F E \nJ A I P U R\n302013\nPH NO. 8055\nADDRESS : SVMPS");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 380, -1));

        jLabel3.setText("F  O  O  D    N  A  M  E");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, -1));

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 230, -1));

        jLabel4.setText("Q  T  Y");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 314, -1, 30));
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 230, -1));

        jLabel5.setText("T  A  X");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 240, -1));

        jLabel6.setText("T O T A L ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));

        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        jPanel1.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 140, -1));

        jLabel7.setText("C U S T O M E R  N A M E ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));
        jPanel1.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 120, -1));

        jLabel9.setText("C U S T O M E R  P H O N E  ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));
        jPanel1.add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("C  A  L  C  U  L  A  T  E  ");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel11.setText("P R I C E");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        T7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T7ActionPerformed(evt);
            }
        });
        jPanel1.add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 140, -1));

        nc8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nc8.setForeground(new java.awt.Color(102, 204, 255));
        nc8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png"))); // NOI18N
        nc8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nc8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nc8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nc8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nc8MouseExited(evt);
            }
        });
        jPanel1.add(nc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 90));

        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "F O O D A V A I L A B L E", "  P R I C E ", "QTY"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        tb2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb2PropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(tb2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 430, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Lock().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked

        J.setVisible(true);
        menu.setVisible(false);
        back.setVisible(true);
      

        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseClicked

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);

        // TODO add your handling code here:
    }//GEN-LAST:event_brMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    J.setVisible(false);
   
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        menu.setVisible(true);
        J.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void SETMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseEntered

        SET.setBackground(new Color(153,0,204));
        {
            SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Settings ROLL.png")));}
        // TODO add your handling code here:
    }//GEN-LAST:event_SETMouseEntered

    private void SETMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseExited
        SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SETTINGS.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_SETMouseExited

    private void AUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseEntered
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INFO ROLL.png")));
    }//GEN-LAST:event_AUMouseEntered

    private void AUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseExited
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png")));
    }//GEN-LAST:event_AUMouseExited

    private void homMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homMouseClicked

        new home().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homMouseClicked

    private void SETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseClicked
new settings().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_SETMouseClicked

    private void AUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseClicked
new about().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_AUMouseClicked

    private void FOODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseClicked

        new food().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FOODMouseClicked

    private void FOODMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseEntered
        // TODO add your handling code here:
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients1.png")));
    }//GEN-LAST:event_FOODMouseEntered

    private void FOODMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseExited
        // TODO add your handling code here:
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients.png")));
    }//GEN-LAST:event_FOODMouseExited

    private void SUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseClicked

        new supplier().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SUPMouseClicked

    private void SUPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseEntered
        // TODO add your handling code here:
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier1.png")));
    }//GEN-LAST:event_SUPMouseEntered

    private void SUPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseExited
        // TODO add your handling code here:
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.png")));
    }//GEN-LAST:event_SUPMouseExited

    private void WAGESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseClicked

        new wages().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_WAGESMouseClicked

    private void WAGESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseEntered
        // TODO add your handling code here:

        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages1.png")));
    }//GEN-LAST:event_WAGESMouseEntered

    private void WAGESMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseExited
        // TODO add your handling code here:
        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages.png")));
    }//GEN-LAST:event_WAGESMouseExited

    private void SALEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseClicked

        new sales().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SALEMouseClicked

    private void SALEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseEntered
        // TODO add your handling code here:
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales1.png")));
    }//GEN-LAST:event_SALEMouseEntered

    private void SALEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseExited
        // TODO add your handling code here:
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png")));
    }//GEN-LAST:event_SALEMouseExited

    private void STOCKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseClicked

        new stocks().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_STOCKMouseClicked

    private void STOCKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseEntered
        // TODO add your handling code here:
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks1.png")));
    }//GEN-LAST:event_STOCKMouseEntered

    private void STOCKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseExited
        // TODO add your handling code here:
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks.png")));
    }//GEN-LAST:event_STOCKMouseExited

    private void EMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseClicked

        new employees().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_EMPMouseClicked

    private void EMPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseEntered
        // TODO add your handling code here:
        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees1.png")));
    }//GEN-LAST:event_EMPMouseEntered

    private void EMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseExited
        // TODO add your handling code here:

        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees.png")));
    }//GEN-LAST:event_EMPMouseExited

    private void bilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseClicked

        new bill().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_bilMouseClicked

    private void bilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseEntered

        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (2).png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_bilMouseEntered

    private void bilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseExited
        // TODO add your handling code here:
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png")));
    }//GEN-LAST:event_bilMouseExited

    private void ncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseClicked
        new customer().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ncMouseClicked

    private void ncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseEntered
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_ncMouseEntered

    private void ncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseExited
        // TODO add your handling code here:
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer1.png")));
    }//GEN-LAST:event_ncMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked



        DefaultTableModel tbld =(DefaultTableModel)tb.getModel();
        int ROW = tbld.getRowCount();
        if(ROW>0){
            for(int i = 0;i<ROW;i++){
                tbld.removeRow(0);
            }
        }
        try{
            Class.forName("java.sql.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st=co.createStatement();
            String q="select FOODNAME,PRICE from food ;";
            ResultSet rs =  st.executeQuery(q);
            while(rs.next()){

                String x = rs.getString("FOODNAME");

                String Z = rs.getString("PRICE");

                tbld.addRow(new Object[]{x,Z});
}

        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ ex.getMessage());}

        





// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
String a = T1.getText();
int b = Integer.parseInt(T2.getText());
String c = T3.getText();
int d = Integer.parseInt(T4.getText());
int e = Integer.parseInt(T5.getText());

T5.setText("20%");
int f = Integer.parseInt(T6.getText());

int g = Integer.parseInt(T7.getText());
     
double sa =g*d;
double tax =sa*0.20;
double to =sa+tax;
T6.setText(""+to);



        



// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void nc8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nc8MouseClicked

    private void nc8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc8MouseEntered
        // TODO add your handling code here:
        nc8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (2).png")));

    }//GEN-LAST:event_nc8MouseEntered

    private void nc8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc8MouseExited
        // TODO add your handling code here:
        nc8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png")));
    }//GEN-LAST:event_nc8MouseExited

    private void tbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbPropertyChange

        

// TODO add your handling code here:
    }//GEN-LAST:event_tbPropertyChange

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
      
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMouseClicked

    private void T7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T7ActionPerformed

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked

        String c = T3.getText();
        
int g = Integer.parseInt(T7.getText());
int d = Integer.parseInt(T4.getText());

        DefaultTableModel tblc = (DefaultTableModel)tb2.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st = con.createStatement();

            String ad = "Insert into bill values('"+c+"',"+g+",'"+d+"');";
            st.executeUpdate(ad);

            tblc.addRow(new Object[]{c,g,d});

        }catch(Exception ae){
            JOptionPane.showMessageDialog(null,""+ae.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseClicked

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add1.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseExited

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb2MouseClicked

    private void tb2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tb2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel AU;
    private javax.swing.JPanel DATE;
    private javax.swing.JLabel EMP;
    private javax.swing.JLabel FOOD;
    private javax.swing.JPanel J;
    private javax.swing.JLabel SALE;
    private javax.swing.JLabel SET;
    private javax.swing.JLabel STOCK;
    private javax.swing.JLabel SUP;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JPanel TIME;
    private javax.swing.JLabel WAGES;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bil;
    private javax.swing.JLabel br;
    private javax.swing.JLabel dat;
    private javax.swing.JLabel hom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel nc;
    private javax.swing.JLabel nc8;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tb;
    private javax.swing.JTable tb2;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
}
