
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ip1;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author komal
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        
           
        //time
         new Timer(1000, new ActionListener(){
         @Override
         
            public void actionPerformed(ActionEvent e) {
                LocalDateTime ldt =LocalDateTime.now();
                 try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= c.createStatement();
            String q = "select curtime(),curdate() ;";
            ResultSet rs=s.executeQuery(q);
            if(rs.next()){

                
                
                 String z=rs.getString("curtime()");
                 String y=rs.getString("curdate()");
                 
                      
                  tim.setText(z);
                  dat.setText(y);
               

            }

        }

        catch (Exception qe){
            JOptionPane.showMessageDialog(null,""+qe.getMessage());
        }
            

            }
        }).start();
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DATE = new javax.swing.JPanel();
        dat = new javax.swing.JLabel();
        TIME = new javax.swing.JPanel();
        tim = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        br = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        pwdf = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        fp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 200));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DATE.setBackground(new java.awt.Color(153, 0, 204));

        dat.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DATELayout = new javax.swing.GroupLayout(DATE);
        DATE.setLayout(DATELayout);
        DATELayout.setHorizontalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DATELayout.setVerticalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        TIME.setBackground(new java.awt.Color(153, 0, 204));

        tim.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        tim.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TIMELayout = new javax.swing.GroupLayout(TIME);
        TIME.setLayout(TIMELayout);
        TIMELayout.setHorizontalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TIMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        TIMELayout.setVerticalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 130, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        jLabel2.setText("P A S S W O R D ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log in.JPG"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 70, 80));

        jLabel3.setText("U S E R N A M E");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 220, -1));
        jPanel1.add(pwdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 220, -1));

        jLabel1.setText("N A M E ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, -1));

        fp.setBackground(new java.awt.Color(0, 102, 204));
        fp.setForeground(new java.awt.Color(0, 153, 204));
        fp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORGOT PWD.JPG"))); // NOI18N
        fp.setText("forgot password ?");
        fp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpMouseClicked(evt);
            }
        });
        jPanel1.add(fp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loguser.JPG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
fp.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void fpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpMouseClicked


        new que().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
}//GEN-LAST:event_fpMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String B = new String(pwdf.getPassword());
        String b = t3.getText();
                String a = t1.getText();


                 if(a.equals("")&&(B.equals("")&&b.equals("")))
     JOptionPane.showMessageDialog(null,"please input data");
                 else{

        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= c.createStatement();
            String q = "select*from k ;";
            ResultSet rs=s.executeQuery(q);
            if(rs.next()){

                String y = rs.getString("pwd");
                String x=rs.getString("UNAME");
                 String z=rs.getString("name");

                    

            if(a.equals(z)&&B.equals(y)&&b.equals(x)){

                 JOptionPane.showMessageDialog(null,"login successful ");
                 { new home().setVisible(true);
            this.dispose();}






            }

            else
                 if(a.equals(z)&&B.equals(y)&&!b.equals(x))
            JOptionPane.showMessageDialog(null,"please enter a suitable username ");

        
             if(a.equals(z)&&!B.equals(y)&&b.equals(x))
            JOptionPane.showMessageDialog(null,"please enter a suitable password ");

          
             if(!a.equals(z)&&B.equals(y)&&b.equals(x))
            JOptionPane.showMessageDialog(null,"enter correct name");





             if(!a.equals(z)&&B.equals(y)&&!b.equals(x))
            JOptionPane.showMessageDialog(null,"enter correct name & username");

             if(!a.equals(z)&&!B.equals(y)&&b.equals(x))
            JOptionPane.showMessageDialog(null,"enter correct name & password");

                  if(a.equals(z)&&!B.equals(y)&&!b.equals(x))
            JOptionPane.showMessageDialog(null,"enter correct username & password");

                



                           
                  if(!a.equals(z)&&!B.equals(y)&&!b.equals(x))
           fp.setVisible(true);


            }
            
            else
                fp.setVisible(true);
             
            

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,""+e.getMessage());
        }

                 }

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);







        // TODO add your handling code here:
}//GEN-LAST:event_brMouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

System.exit(0);        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DATE;
    private javax.swing.JPanel TIME;
    private javax.swing.JLabel br;
    private javax.swing.JLabel dat;
    private javax.swing.JLabel fp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwdf;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
}
