/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author komal
 */
public class que extends javax.swing.JFrame {

    /**
     * Creates new form que
     */
    public que() {
        initComponents();
    
        
        //time
         new Timer(1000, new ActionListener(){
         @Override
         
            public void actionPerformed(ActionEvent e) {
                LocalDateTime ldt =LocalDateTime.now();
                 try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= c.createStatement();
            String q = "select curtime(),curdate() ;";
            ResultSet rs=s.executeQuery(q);
            if(rs.next()){

                
                
                 String z=rs.getString("curtime()");
                 String y=rs.getString("curdate()");
                 
                      
                  tim.setText(z);
                  dat.setText(y);
               

            }

        }

        catch (Exception qe){
            JOptionPane.showMessageDialog(null,""+qe.getMessage());
        }
            

            }
        }).start();
                        
                
    }

    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DATE = new javax.swing.JPanel();
        dat = new javax.swing.JLabel();
        TIME = new javax.swing.JPanel();
        tim = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        br = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        J = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        AU = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CB = new javax.swing.JComboBox();
        T1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Long_Arrow_Left_48px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        DATE.setBackground(new java.awt.Color(153, 0, 204));

        dat.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DATELayout = new javax.swing.GroupLayout(DATE);
        DATE.setLayout(DATELayout);
        DATELayout.setHorizontalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DATELayout.setVerticalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 40));

        TIME.setBackground(new java.awt.Color(153, 0, 204));

        tim.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        tim.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TIMELayout = new javax.swing.GroupLayout(TIME);
        TIME.setLayout(TIMELayout);
        TIMELayout.setHorizontalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TIMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        TIMELayout.setVerticalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 130, 40));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.JPG"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submit.JPG"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, 50));

        J.setBackground(new java.awt.Color(153, 0, 204));

        back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        AU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AU.setForeground(new java.awt.Color(255, 255, 255));
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png"))); // NOI18N
        AU.setText("A B O U T  U S ");
        AU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JLayout = new javax.swing.GroupLayout(J);
        J.setLayout(JLayout);
        JLayout.setHorizontalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back))
            .addGroup(JLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JLayout.setVerticalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLayout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AU)
                .addContainerGap())
        );

        jPanel1.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 260));

        jLabel2.setText("ENTER YOUR SECURITY QUESTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WHICH IS YOUR FAV PET?", "WHO ARE YOU?", "WHICH IS YOUR FAV FRUIT?", "WHICH IS YOUR FAV COLOUR?" }));
        jPanel1.add(CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, -1));
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 140, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/ezgif.com-gif-maker(1).gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String A = (String) CB.getSelectedItem();
        String b = T1.getText();
        
        if(b.isEmpty())
        JOptionPane.showMessageDialog(null,"please enter your security question");    
        else
        
        try{
            Class.forName("java.sql.Driver");
            Connection co = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= co.createStatement();
        
                
            String qs = "Select*from que;";
           ResultSet rs= s.executeQuery(qs);
           if(rs.next()){
               
                 String y = rs.getString("Q");
                String x=rs.getString("A");
                
                   if(A.equals(y)&&b.equals(x)){
                       new forgotpassword().setVisible(true);
                       this.dispose();
                 }else
                    JOptionPane.showMessageDialog(null,"wrong security key");
               
           }
    
           
    else
               
           try{
        
        
            String q = "insert into que values('"+A+"','"+b+"');";
            s.executeUpdate(q);
           }catch(Exception r){
            JOptionPane.showMessageDialog(null," "+ r.getMessage());}
   
           }
              


        
        catch(Exception e){
            JOptionPane.showMessageDialog(null," "+ e.getMessage());}

        

            
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);

        // TODO add your handling code here:
    }//GEN-LAST:event_brMouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked

        J.setVisible(true);
        menu.setVisible(false);
         back.setVisible(true);
        

// TODO add your handling code here:
    }//GEN-LAST:event_menuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
J.setVisible(false);
     
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        menu.setVisible(true);
        J.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
new Login().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseEntered
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INFO ROLL.png")));
    }//GEN-LAST:event_AUMouseEntered

    private void AUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseExited
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png")));
    }//GEN-LAST:event_AUMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(que.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new que().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AU;
    private javax.swing.JComboBox CB;
    private javax.swing.JPanel DATE;
    private javax.swing.JPanel J;
    private javax.swing.JTextField T1;
    private javax.swing.JPanel TIME;
    private javax.swing.JLabel back;
    private javax.swing.JLabel br;
    private javax.swing.JLabel dat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
}
