/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VIKASH
 */
public class sales extends javax.swing.JFrame {

    /**
     * Creates new form sales
     */
    public sales() {
        initComponents();
         //time
         new Timer(1000, new ActionListener(){
         @Override
         
            public void actionPerformed(ActionEvent e) {
                LocalDateTime ldt =LocalDateTime.now();
                 try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= c.createStatement();
            String q = "select curtime(),curdate() ;";
            ResultSet rs=s.executeQuery(q);
            if(rs.next()){

                
                
                 String z=rs.getString("curtime()");
                 String y=rs.getString("curdate()");
                 
                      
                  tim.setText(z);
                  dat.setText(y);
               

            }

        }

        catch (Exception qe){
            JOptionPane.showMessageDialog(null,""+qe.getMessage());
        }
            

            }
        }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DATE = new javax.swing.JPanel();
        dat = new javax.swing.JLabel();
        TIME = new javax.swing.JPanel();
        tim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        br = new javax.swing.JLabel();
        J = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        SET = new javax.swing.JLabel();
        AU = new javax.swing.JLabel();
        hom = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        FOOD = new javax.swing.JLabel();
        SUP = new javax.swing.JLabel();
        WAGES = new javax.swing.JLabel();
        SALE = new javax.swing.JLabel();
        STOCK = new javax.swing.JLabel();
        EMP = new javax.swing.JLabel();
        bil = new javax.swing.JLabel();
        nc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nc4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        ADD = new javax.swing.JLabel();
        DELETE = new javax.swing.JLabel();
        SEARCH = new javax.swing.JLabel();
        UPDATE = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(110, 110));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DATE.setBackground(new java.awt.Color(153, 0, 204));

        dat.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        dat.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DATELayout = new javax.swing.GroupLayout(DATE);
        DATE.setLayout(DATELayout);
        DATELayout.setHorizontalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DATELayout.setVerticalGroup(
            DATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 40));

        TIME.setBackground(new java.awt.Color(153, 0, 204));

        tim.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        tim.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TIMELayout = new javax.swing.GroupLayout(TIME);
        TIME.setLayout(TIMELayout);
        TIMELayout.setHorizontalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TIMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        TIMELayout.setVerticalGroup(
            TIMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tim, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.JPG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 40));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.JPG"))); // NOI18N
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        J.setBackground(new java.awt.Color(153, 0, 204));

        back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("<");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        SET.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SET.setForeground(new java.awt.Color(255, 255, 255));
        SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SETTINGS.png"))); // NOI18N
        SET.setText("S E T T I N G S ");
        SET.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETMouseExited(evt);
            }
        });

        AU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AU.setForeground(new java.awt.Color(255, 255, 255));
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png"))); // NOI18N
        AU.setText("A B O U T  U S ");
        AU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AUMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JLayout = new javax.swing.GroupLayout(J);
        J.setLayout(JLayout);
        JLayout.setHorizontalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLayout.createSequentialGroup()
                .addGap(0, 174, Short.MAX_VALUE)
                .addComponent(back))
            .addGroup(JLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JLayout.setVerticalGroup(
            JLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLayout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(SET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AU)
                .addGap(13, 13, 13))
        );

        jPanel1.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 540));

        hom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.JPG"))); // NOI18N
        hom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homMouseClicked(evt);
            }
        });
        jPanel1.add(hom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        sp.setBackground(new java.awt.Color(255, 255, 255));
        sp.setBorder(null);
        sp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sp.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        sp.setDoubleBuffered(true);
        sp.setFocusCycleRoot(true);
        sp.setInheritsPopupMenu(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FOOD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FOOD.setForeground(new java.awt.Color(255, 0, 204));
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients.png"))); // NOI18N
        FOOD.setText("I N G R E D I E N T S");
        FOOD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FOOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FOODMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FOODMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FOODMouseExited(evt);
            }
        });
        jPanel2.add(FOOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 110));

        SUP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SUP.setForeground(new java.awt.Color(0, 102, 255));
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.png"))); // NOI18N
        SUP.setText("S U P P L I E R");
        SUP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUPMouseExited(evt);
            }
        });
        jPanel2.add(SUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 110));

        WAGES.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WAGES.setForeground(new java.awt.Color(255, 255, 0));
        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages.png"))); // NOI18N
        WAGES.setText("W A G E S");
        WAGES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WAGES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WAGESMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WAGESMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WAGESMouseExited(evt);
            }
        });
        jPanel2.add(WAGES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 110));

        SALE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SALE.setForeground(new java.awt.Color(102, 0, 255));
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png"))); // NOI18N
        SALE.setText("S A L E S");
        SALE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SALE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SALEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SALEMouseExited(evt);
            }
        });
        jPanel2.add(SALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 110));

        STOCK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        STOCK.setForeground(new java.awt.Color(255, 153, 51));
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks.png"))); // NOI18N
        STOCK.setText("S T O C K S");
        STOCK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STOCK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STOCKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STOCKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STOCKMouseExited(evt);
            }
        });
        jPanel2.add(STOCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 110));

        EMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EMP.setForeground(new java.awt.Color(51, 0, 255));
        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees.png"))); // NOI18N
        EMP.setText("E M P L O Y E E S");
        EMP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EMPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EMPMouseExited(evt);
            }
        });
        jPanel2.add(EMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 230, 110));

        bil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bil.setForeground(new java.awt.Color(153, 255, 0));
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png"))); // NOI18N
        bil.setText("B  I  L  L ");
        bil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilMouseExited(evt);
            }
        });
        jPanel2.add(bil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 110));

        nc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nc.setForeground(new java.awt.Color(102, 204, 255));
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer1.png"))); // NOI18N
        nc.setText("N E W  C U S T O M E R");
        nc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ncMouseExited(evt);
            }
        });
        jPanel2.add(nc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 260, 110));

        sp.setViewportView(jPanel2);

        jPanel1.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 40, -1, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("    S   A   L   E   S ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        nc4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nc4.setForeground(new java.awt.Color(102, 204, 255));
        nc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png"))); // NOI18N
        nc4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nc4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nc4MouseExited(evt);
            }
        });
        jPanel1.add(nc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 90));

        jLabel3.setText("SNO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel4.setText("NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jLabel5.setText("LOCID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, 20));

        jLabel6.setText("CITY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 140, -1));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 200, -1));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 160, -1));
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 180, -1));

        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.JPG"))); // NOI18N
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETEMouseExited(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        SEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        SEARCH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SEARCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEARCHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEARCHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEARCHMouseExited(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPDATEMouseExited(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel8.setText("REFRESH TABLE ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        tbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "NAME", "SALES", "LOCID", "CITY"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 340, 700, 230));

        jLabel7.setText("SALES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
        jPanel1.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Lock().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked

        J.setVisible(true);
        menu.setVisible(false);
        back.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseClicked

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);

        // TODO add your handling code here:
    }//GEN-LAST:event_brMouseDragged

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        menu.setVisible(true);
        J.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void SETMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseEntered

        SET.setBackground(new Color(153,0,204));
        {
            SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Settings ROLL.png")));}
        // TODO add your handling code here:
    }//GEN-LAST:event_SETMouseEntered

    private void SETMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseExited
        SET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SETTINGS.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_SETMouseExited

    private void AUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseEntered
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INFO ROLL.png")));
    }//GEN-LAST:event_AUMouseEntered

    private void AUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseExited
        // TODO add your handling code here:
        AU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info_Squared_48px_1.png")));
    }//GEN-LAST:event_AUMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
J.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void homMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homMouseClicked

        new home().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homMouseClicked

    private void SETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETMouseClicked
new settings().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_SETMouseClicked

    private void AUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AUMouseClicked
new about().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_AUMouseClicked

    private void FOODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseClicked

        new food().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FOODMouseClicked

    private void FOODMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseEntered
        // TODO add your handling code here:
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients1.png")));
    }//GEN-LAST:event_FOODMouseEntered

    private void FOODMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOODMouseExited
        // TODO add your handling code here:
        FOOD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ingredients.png")));
    }//GEN-LAST:event_FOODMouseExited

    private void SUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseClicked

        new supplier().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SUPMouseClicked

    private void SUPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseEntered
        // TODO add your handling code here:
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier1.png")));
    }//GEN-LAST:event_SUPMouseEntered

    private void SUPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUPMouseExited
        // TODO add your handling code here:
        SUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Supplier.png")));
    }//GEN-LAST:event_SUPMouseExited

    private void WAGESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseClicked

        new wages().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_WAGESMouseClicked

    private void WAGESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseEntered
        // TODO add your handling code here:

        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages1.png")));
    }//GEN-LAST:event_WAGESMouseEntered

    private void WAGESMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WAGESMouseExited
        // TODO add your handling code here:
        WAGES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wages.png")));
    }//GEN-LAST:event_WAGESMouseExited

    private void SALEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseClicked

        new sales().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SALEMouseClicked

    private void SALEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseEntered
        // TODO add your handling code here:
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales1.png")));
    }//GEN-LAST:event_SALEMouseEntered

    private void SALEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALEMouseExited
        // TODO add your handling code here:
        SALE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png")));
    }//GEN-LAST:event_SALEMouseExited

    private void STOCKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseClicked

        new stocks().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_STOCKMouseClicked

    private void STOCKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseEntered
        // TODO add your handling code here:
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks1.png")));
    }//GEN-LAST:event_STOCKMouseEntered

    private void STOCKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKMouseExited
        // TODO add your handling code here:
        STOCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stocks.png")));
    }//GEN-LAST:event_STOCKMouseExited

    private void EMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseClicked

        new employees().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_EMPMouseClicked

    private void EMPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseEntered
        // TODO add your handling code here:
        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees1.png")));
    }//GEN-LAST:event_EMPMouseEntered

    private void EMPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMPMouseExited
        // TODO add your handling code here:

        EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employees.png")));
    }//GEN-LAST:event_EMPMouseExited

    private void bilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseClicked

        new bill().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_bilMouseClicked

    private void bilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseEntered

        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (2).png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_bilMouseEntered

    private void bilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseExited
        // TODO add your handling code here:
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill (1).png")));
    }//GEN-LAST:event_bilMouseExited

    private void ncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseClicked
        new customer().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ncMouseClicked

    private void ncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseEntered
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_ncMouseEntered

    private void ncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncMouseExited
        // TODO add your handling code here:
        nc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer1.png")));
    }//GEN-LAST:event_ncMouseExited

    private void nc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nc4MouseClicked

    private void nc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc4MouseEntered
        nc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales1.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_nc4MouseEntered

    private void nc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nc4MouseExited
        // TODO add your handling code here:

        nc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sales.png")));
    }//GEN-LAST:event_nc4MouseExited

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked

        //add

        int a=Integer.parseInt(t1.getText());
        String b=t2.getText();
        int c=Integer.parseInt(t3.getText());
        
        String f=t4.getText();
        int P=Integer.parseInt(T5.getText());
        
        DefaultTableModel tblc = (DefaultTableModel)tbl.getModel();

        try{
            Class.forName("java.sql.Driver");
            Connection co = DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement s= co.createStatement();
            String q = "insert into sales values("+a+",'"+b+"',"+P+","+c+",'"+f+"');";
            s.executeUpdate(q);

            tblc.addRow(new Object[]{a,b,P,c,f});

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null," "+ e.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseClicked

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add1.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDMouseExited

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked

        //delete

        int a=Integer.parseInt(t1.getText());

        DefaultTableModel tbld =(DefaultTableModel)tbl.getModel();
        int ROW = tbld.getRowCount();
        if(ROW>0){
            for(int i = 0;i<ROW;i++){
                tbld.removeRow(0);
            }
        }
        try{
            Class.forName("java.sql.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st=co.createStatement();
            String q="delete from sales where SNO="+a+";";
            st.executeUpdate(q);

            String rt = "select*from sales";
            ResultSet rs =  st.executeQuery(rt);
            while(rs.next()){
                int z = rs.getInt("SNO");
                String y = rs.getString("NAME");
                int S = rs.getInt("SALES");
                int w = rs.getInt("LOCID");
               String x = rs.getString("CITY");

                tbld.addRow(new Object[]{ z,y,S,w,x});

            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ ex.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseClicked

    private void DELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseEntered
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete1.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseEntered

    private void DELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseExited
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.JPG")));
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseExited

    private void SEARCHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCHMouseClicked

        //SEARCH
        int a=Integer.parseInt(t1.getText());

        t2.setText(" ");
        t3.setText(" ");
        t4.setText(" ");


        DefaultTableModel tbld =(DefaultTableModel)tbl.getModel();
        int ROW = tbld.getRowCount();
        if(ROW>0){
            for(int i = 0;i<ROW;i++){
                tbld.removeRow(0);
            }
        }
        try{
            Class.forName("java.sql.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st=co.createStatement();
            String q="select*from sales where SNO="+a+";";
            ResultSet rs =  st.executeQuery(q);
            while(rs.next()){

                int z = rs.getInt("SNO");
                String y = rs.getString("NAME");
                 int S = rs.getInt("SALES");
                int w = rs.getInt("LOCID");
               String x = rs.getString("CITY");

                tbld.addRow(new Object[]{ z,y,S,w,x});
}

        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ ex.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHMouseClicked

    private void SEARCHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCHMouseEntered
        SEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.JPG")));
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHMouseEntered

    private void SEARCHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCHMouseExited
        SEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHMouseExited

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        //update


        int a=Integer.parseInt(t1.getText());
        String b=t2.getText();
        int c=Integer.parseInt(t3.getText());
        
        int P=Integer.parseInt(T5.getText());
        
        String f=t4.getText();
        DefaultTableModel tbld =(DefaultTableModel)tbl.getModel();
        int ROW = tbld.getRowCount();
        if(ROW>0){
            for(int i = 0;i<ROW;i++){
                tbld.removeRow(0);
            }
        }

        try{
            Class.forName("java.sql.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st=co.createStatement();
            String q="update sales set NAME = '"+b+"',SALES = "+P+",LOCID="+c+",CITY= '"+f+"' where SNO ="+a+";";
            st.executeUpdate(q);

            String rt = "select*from stock";
            ResultSet rs =  st.executeQuery(rt);
            while(rs.next()){
                
                int z = rs.getInt("SNO");
                String y = rs.getString("NAME");
                 int S = rs.getInt("SALES");
                int w = rs.getInt("LOCID");
               String x = rs.getString("CITY");

                tbld.addRow(new Object[]{ z,y,S,w,x});

            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ ex.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseClicked

    private void UPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseEntered
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update1.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseEntered

    private void UPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseExited
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        DefaultTableModel tbld =(DefaultTableModel)tbl.getModel();
        int ROW = tbld.getRowCount();
        if(ROW>0){
            for(int i = 0;i<ROW;i++){
                tbld.removeRow(0);
            }
        }    try{
            Class.forName("java.sql.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost/mukul","root","");
            Statement st=co.createStatement();

            String rt = "select*from sales";
            ResultSet rs =  st.executeQuery(rt);
            while(rs.next()){
                int z = rs.getInt("SNO");
                String y = rs.getString("NAME");
                 int S = rs.getInt("SALES"); 
                int w = rs.getInt("LOCID");
               String x = rs.getString("CITY");

                tbld.addRow(new Object[]{ z,y,S,w,x});

                
            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ ex.getMessage());}

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel AU;
    private javax.swing.JPanel DATE;
    private javax.swing.JLabel DELETE;
    private javax.swing.JLabel EMP;
    private javax.swing.JLabel FOOD;
    private javax.swing.JPanel J;
    private javax.swing.JLabel SALE;
    private javax.swing.JLabel SEARCH;
    private javax.swing.JLabel SET;
    private javax.swing.JLabel STOCK;
    private javax.swing.JLabel SUP;
    private javax.swing.JTextField T5;
    private javax.swing.JPanel TIME;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel WAGES;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bil;
    private javax.swing.JLabel br;
    private javax.swing.JLabel dat;
    private javax.swing.JLabel hom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel nc;
    private javax.swing.JLabel nc4;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables
}
