/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip1;

/**
 *
 * @author VIKASH
 */
public class settings extends javax.swing.JFrame {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        br = new javax.swing.JLabel();
        RP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(190, 190));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2 - Copy.JPG"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 40));

        br.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        br.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brMouseDragged(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        RP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change password.JPG"))); // NOI18N
        RP.setText("R E S E T  P A S S W O R D ");
        RP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RPMouseExited(evt);
            }
        });
        jPanel1.add(RP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void brMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);

        // TODO add your handling code here:
    }//GEN-LAST:event_brMouseDragged

    private void RPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMouseEntered
  RP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change password1.png")));
        
// TODO add your handling code here:
    }//GEN-LAST:event_RPMouseEntered

    private void RPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMouseExited
 RP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change password.JPG")));
 // TODO add your handling code here:
    }//GEN-LAST:event_RPMouseExited

    private void RPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPMouseClicked
new que().setVisible(true);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_RPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RP;
    private javax.swing.JLabel br;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
